---
uptime_kuma_image: louislam/uptime-kuma:2.5.0
uptime_kuma_alpine_image: alpine:3.22
uptime_kuma_container_name: uptime-kuma
uptime_kuma_volume_name: uptime-kuma-data
uptime_kuma_app_dir: /opt/uptime-kuma
uptime_kuma_backup_dir: /mnt/uptime-kuma-backups
uptime_kuma_backup_calendar: "*-*-* 00,06,12,18:00:00"
uptime_kuma_backup_random_delay: 5m
uptime_kuma_local_port: 3001
