---
gitops_controller_user: hasan
gitops_controller_group: "{{ gitops_controller_user }}"
gitops_controller_user_home: "/home/{{ gitops_controller_user }}"

gitops_controller_repo_url: >-
  https://github.com/lhasanseker/gitops-iac-project.git
gitops_controller_branch: main
gitops_controller_root: /opt/gitops-controller
gitops_controller_repo_dir: "{{ gitops_controller_root }}/repository"
gitops_controller_state_dir: /var/lib/gitops-controller
gitops_controller_state_file: >-
  {{ gitops_controller_state_dir }}/last-successful-commit
gitops_controller_private_key: >-
  {{ gitops_controller_user_home }}/.ssh/gitops_iac_vagrant

gitops_controller_inventory_path: ansible/inventory.ini
gitops_controller_playbook_path: ansible/site.yml
gitops_controller_health_url: http://192.168.56.10

gitops_controller_timer_on_boot: 2min
gitops_controller_timer_interval: 1min
gitops_controller_timer_random_delay: 15s
