services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.5.0
    container_name: uptime-kuma
    restart: unless-stopped

    environment:
      TZ: Europe/Istanbul

    ports:
      - "127.0.0.1:3001:3001"

    volumes:
      - uptime-kuma-data:/app/data

    security_opt:
      - no-new-privileges:true

volumes:
  uptime-kuma-data:
    external: true
    name: uptime-kuma-data
